[project]
name = "llm_service"
version = "0.1.0"
dependencies = [
    "fastapi==0.124.4",
    "uvicorn==0.38.0",
    "pydantic==2.12.5",
    "python-dotenv==1.2.1",
    "groq",
]

[project.optional-dependencies]
dev = [
]
