version: '3.8'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  postgres:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dbname
    ports:
      - "5432:5432"

  llm-service:
    build: ./llm_service
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}

  backend:
    build: ./backend
    ports:
      - "8001:8001"
    environment:
      - PYTHONUNBUFFERED=1
      - BOT_TOKEN=${BOT_TOKEN}
      - DATABASE_URL=postgresql://user:password@postgres/dbname
    depends_on:
      - redis
      - postgres

  celery-worker:
    build: ./backend
    command: uv run celery -A app.celery_app worker --loglevel=info
    environment:
      - PYTHONUNBUFFERED=1
      - BOT_TOKEN=${BOT_TOKEN}
      - DATABASE_URL=postgresql://user:password@postgres/dbname
    depends_on:
      - redis
      - backend
      - postgres

  celery-beat:
    build: ./backend
    command: uv run celery -A app.celery_app beat --loglevel=info
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://user:password@postgres/dbname
    depends_on:
      - redis
      - celery-worker

  frontend:
    build: ./frontend
    ports:
      - "22222:80"
    depends_on:
      - backend

  telegram-bot:
    build: ./telegram_bot
    environment:
      - PYTHONUNBUFFERED=1
      - BOT_TOKEN=${BOT_TOKEN}
    depends_on:
      - llm-service
      - backend
      - frontend

  flower:
    image: mher/flower:2.0.1
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - celery-worker

volumes:
  postgres_data:
